export const headers = {
  categories: [
    { id: 'name', label: 'Name', editable: true },
    { id: 'description', label: 'Description', editable: true },
    { id: '_id', label: 'ID', editable: false },
  ],
  products: [
    { id: 'name', label: 'Name', editable: false },
    { id: 'description', label: 'Description', editable: true },
    { id: 'price', label: 'Price' },
    { id: '_id', label: 'ID' },
  ],
  //   palette: [
  //   { id: 'name', isHeader: true, label: 'Name', editable: true },
  //   { id: 'primaryColor', isHeader: true, label: 'Primary Color', editable: true, isColor: true },
  //   { id: 'secondaryColor', isHeader: true, label: 'Secondary Color', editable: true, isColor: true },
  //   { id: 'backgroundColor', isHeader: true, label: 'Background Color', editable: true, isColor: true },
  //   { id: 'textColor', isHeader: false, label: 'Text Color', editable: true },
  //   { id: 'smallLogo', isHeader: false, label: 'Small Logo', editable: true },
  //   { id: 'largeLogo', isHeader: false, label: 'Large Logo', editable: true },
  //   { id: 'fontFamily', isHeader: false, label: 'Font Family', editable: true },
  //   { id: 'isActive', isHeader: false, label: 'Is Active', editable: true },
  //   { id: 'createdAt', isHeader: false, label: 'Created At', editable: false },
  //   { id: 'storeId', isHeader: true, label: 'Store ID', editable: true },
  //   { id: 'updatedAt', isHeader: false, label: 'Updated At', editable: false },
  // ],

  stores: [
    // {
    //   id: '_id',
    //   label: 'ID',
    //   editable: false,
    //   isHeader: false,
    //   required: false,
    //   type: 'text',
    // },
    // {
    //   id: 'primaryColor',
    //   label: 'Primary Color',
    //   editable: true,
    //   isHeader: false,
    //   required: true,
    //   type: 'color',
    // },
    // {
    //   id: 'secondaryColor',
    //   label: 'Secondary Color',
    //   editable: true,
    //   isHeader: false,
    //   required: true,
    //   type: 'color',
    // },
    // {
    //   id: 'palette.backgroundColor',
    //   label: 'Background Color',
    //   editable: true,
    //   isHeader: false,
    //   required: true,
    //   type: 'color',
    // },
    // {
    //   id: 'palette.textColor',
    //   label: 'Text Color',
    //   editable: true,
    //   isHeader: false,
    //   required: true,
    //   type: 'color',
    // },
    // {
    //   id: 'palette.smallLogo',
    //   label: 'Small Logo',
    //   editable: true,
    //   isHeader: false,
    //   required: true,
    //   type: 'url',
    // },
    // {
    //   id: 'palette.largeLogo',
    //   label: 'Large Logo',
    //   editable: true,
    //   isHeader: false,
    //   required: true,
    //   type: 'url',
    // },
    // {
    //   id: 'palette.fontFamily',
    //   label: 'Font Family',
    //   editable: true,
    //   isHeader: false,
    //   required: true,
    //   type: 'text',
    // },
  ],

  users: [
    { id: 'name', label: 'Name', editable: true },
    { id: 'email', label: 'Email', editable: true },
    { id: 'role', label: 'Role', editable: true },
    { id: '_id', label: 'ID', editable: false },
  ],
  orders: [
    { id: 'user', label: 'User', editable: false },
    { id: 'products', label: 'Products', editable: false },
    { id: 'total', label: 'Total', editable: false },
    { id: '_id', label: 'ID', editable: false },
  ],
};
